// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sha256_sha256,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.643000,HLS_SYN_LAT=153,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=416,HLS_SYN_LUT=1404,HLS_VERSION=2020_2}" *)

module sha256 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stateREG_i,
        stateREG_o,
        stateREG_o_ap_vld,
        data,
        hash_address0,
        hash_ce0,
        hash_we0,
        hash_d0,
        hash_address1,
        hash_ce1,
        hash_we1,
        hash_d1
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_pp1_stage0 = 12'd8;
parameter    ap_ST_fsm_state6 = 12'd16;
parameter    ap_ST_fsm_pp2_stage0 = 12'd32;
parameter    ap_ST_fsm_state9 = 12'd64;
parameter    ap_ST_fsm_state10 = 12'd128;
parameter    ap_ST_fsm_state11 = 12'd256;
parameter    ap_ST_fsm_state12 = 12'd512;
parameter    ap_ST_fsm_state13 = 12'd1024;
parameter    ap_ST_fsm_state14 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] stateREG_i;
output  [31:0] stateREG_o;
output   stateREG_o_ap_vld;
input  [7:0] data;
output  [4:0] hash_address0;
output   hash_ce0;
output   hash_we0;
output  [7:0] hash_d0;
output  [4:0] hash_address1;
output   hash_ce1;
output   hash_we1;
output  [7:0] hash_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stateREG_o_ap_vld;
reg[4:0] hash_address0;
reg hash_ce0;
reg hash_we0;
reg[4:0] hash_address1;
reg hash_ce1;
reg hash_we1;
reg[7:0] hash_d1;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] k_address0;
reg    k_ce0;
wire   [31:0] k_q0;
reg   [6:0] i_1_reg_395;
reg   [6:0] i_2_reg_407;
reg   [31:0] a_3_reg_418;
wire   [31:0] or_ln22_1_fu_440_p5;
reg   [31:0] or_ln22_1_reg_1145;
wire   [4:0] add_ln20_fu_452_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln23_fu_469_p2;
reg   [0:0] icmp_ln23_reg_1158;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state4_pp1_stage0_iter0;
wire    ap_block_state5_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [6:0] add_ln23_fu_475_p2;
reg   [6:0] add_ln23_reg_1162;
reg    ap_enable_reg_pp1_iter0;
reg   [31:0] a_reg_1230;
wire    ap_CS_fsm_state6;
wire   [6:0] add_ln37_fu_693_p2;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state7_pp2_stage0_iter0;
wire    ap_block_state8_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln37_fu_699_p2;
reg   [0:0] icmp_ln37_reg_1241;
wire   [31:0] a_2_fu_1005_p2;
reg    ap_enable_reg_pp2_iter1;
wire   [31:0] add_ln52_fu_1016_p2;
reg   [31:0] add_ln52_reg_1260;
wire    ap_CS_fsm_state9;
wire   [2:0] add_ln66_fu_1021_p2;
reg   [2:0] add_ln66_reg_1265;
wire    ap_CS_fsm_state10;
wire   [7:0] trunc_ln67_1_fu_1060_p1;
reg   [7:0] trunc_ln67_1_reg_1273;
wire   [0:0] icmp_ln66_fu_1027_p2;
wire  signed [2:0] xor_ln68_fu_1064_p2;
reg  signed [2:0] xor_ln68_reg_1278;
wire  signed [3:0] or_ln3_fu_1075_p3;
reg  signed [3:0] or_ln3_reg_1284;
wire    ap_CS_fsm_state3;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state4;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_flush_enable;
reg   [5:0] m_address0;
reg    m_ce0;
reg    m_we0;
reg   [31:0] m_d0;
wire   [31:0] m_q0;
wire   [5:0] m_address1;
reg    m_ce1;
wire   [31:0] m_q1;
wire   [5:0] m_address2;
reg    m_ce2;
wire   [31:0] m_q2;
wire   [5:0] m_address3;
reg    m_ce3;
wire   [31:0] m_q3;
wire   [5:0] m_address4;
reg    m_ce4;
wire   [31:0] m_q4;
reg   [4:0] i_reg_384;
wire   [0:0] icmp_ln20_fu_458_p2;
reg   [6:0] ap_phi_mux_i_1_phi_fu_399_p4;
wire    ap_block_pp1_stage0;
reg   [2:0] r_reg_428;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln20_fu_464_p1;
wire   [63:0] zext_ln24_fu_491_p1;
wire   [63:0] zext_ln24_1_fu_502_p1;
wire   [63:0] zext_ln24_2_fu_513_p1;
wire   [63:0] zext_ln24_3_fu_524_p1;
wire   [63:0] zext_ln23_fu_529_p1;
wire   [63:0] zext_ln37_fu_705_p1;
wire    ap_block_pp2_stage0;
wire   [63:0] zext_ln68_fu_1070_p1;
wire   [63:0] zext_ln69_fu_1083_p1;
wire   [63:0] zext_ln66_fu_1088_p1;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln70_fu_1096_p1;
wire   [63:0] zext_ln71_fu_1113_p1;
wire    ap_CS_fsm_state12;
wire   [63:0] zext_ln72_fu_1124_p1;
wire   [63:0] zext_ln73_fu_1132_p1;
wire   [63:0] zext_ln74_fu_1140_p1;
reg   [31:0] h_fu_178;
reg   [31:0] h_1_fu_182;
reg   [31:0] g_fu_186;
reg   [31:0] f_fu_190;
wire   [31:0] e_fu_993_p2;
reg   [31:0] d_fu_194;
reg   [31:0] d_1_fu_198;
reg   [31:0] c_fu_202;
wire   [31:0] add_ln24_6_fu_686_p2;
wire   [5:0] trunc_ln23_fu_481_p1;
wire   [5:0] add_ln24_fu_485_p2;
wire   [5:0] add_ln24_1_fu_496_p2;
wire   [5:0] add_ln24_2_fu_507_p2;
wire   [5:0] add_ln24_3_fu_518_p2;
wire   [16:0] trunc_ln24_fu_544_p1;
wire   [14:0] lshr_ln_fu_534_p4;
wire   [18:0] trunc_ln24_1_fu_566_p1;
wire   [12:0] lshr_ln24_1_fu_556_p4;
wire   [21:0] lshr_ln24_2_fu_578_p4;
wire   [31:0] zext_ln24_4_fu_588_p1;
wire   [31:0] or_ln24_1_fu_570_p3;
wire   [31:0] xor_ln24_fu_592_p2;
wire   [31:0] or_ln_fu_548_p3;
wire   [6:0] trunc_ln24_2_fu_614_p1;
wire   [24:0] lshr_ln24_3_fu_604_p4;
wire   [17:0] trunc_ln24_3_fu_636_p1;
wire   [13:0] lshr_ln24_4_fu_626_p4;
wire   [28:0] lshr_ln24_5_fu_648_p4;
wire   [31:0] zext_ln24_5_fu_658_p1;
wire   [31:0] or_ln24_3_fu_640_p3;
wire   [31:0] xor_ln24_2_fu_662_p2;
wire   [31:0] or_ln24_2_fu_618_p3;
wire   [31:0] xor_ln24_1_fu_598_p2;
wire   [31:0] xor_ln24_3_fu_668_p2;
wire   [31:0] add_ln24_5_fu_680_p2;
wire   [31:0] add_ln24_4_fu_674_p2;
wire   [5:0] trunc_ln38_fu_775_p1;
wire   [25:0] lshr_ln1_fu_765_p4;
wire   [10:0] trunc_ln38_1_fu_797_p1;
wire   [20:0] lshr_ln38_1_fu_787_p4;
wire   [24:0] trunc_ln38_2_fu_819_p1;
wire   [6:0] lshr_ln38_2_fu_809_p4;
wire   [31:0] or_ln1_fu_779_p3;
wire   [31:0] or_ln38_1_fu_801_p3;
wire   [31:0] xor_ln38_fu_831_p2;
wire   [31:0] or_ln38_2_fu_823_p3;
wire   [31:0] xor_ln38_2_fu_849_p2;
wire   [31:0] and_ln38_1_fu_855_p2;
wire   [31:0] and_ln38_fu_843_p2;
wire   [31:0] xor_ln38_3_fu_861_p2;
wire   [31:0] xor_ln38_1_fu_837_p2;
wire   [31:0] add_ln38_1_fu_873_p2;
wire   [31:0] add_ln38_2_fu_879_p2;
wire   [31:0] add_ln38_fu_867_p2;
wire   [1:0] trunc_ln39_fu_901_p1;
wire   [29:0] lshr_ln2_fu_891_p4;
wire   [12:0] trunc_ln39_1_fu_923_p1;
wire   [18:0] lshr_ln39_1_fu_913_p4;
wire   [21:0] trunc_ln39_2_fu_945_p1;
wire   [9:0] lshr_ln39_2_fu_935_p4;
wire   [31:0] or_ln2_fu_905_p3;
wire   [31:0] or_ln39_1_fu_927_p3;
wire   [31:0] xor_ln39_fu_957_p2;
wire   [31:0] or_ln39_2_fu_949_p3;
wire   [31:0] xor_ln39_2_fu_969_p2;
wire   [31:0] and_ln39_fu_975_p2;
wire   [31:0] and_ln39_1_fu_981_p2;
wire   [31:0] t1_fu_885_p2;
wire   [31:0] xor_ln39_1_fu_963_p2;
wire   [31:0] add_ln47_fu_999_p2;
wire   [31:0] xor_ln39_3_fu_987_p2;
wire   [1:0] trunc_ln67_fu_1033_p1;
wire   [4:0] shl_ln_fu_1037_p3;
wire   [4:0] sub_ln67_fu_1045_p2;
wire   [31:0] zext_ln67_fu_1051_p1;
wire   [31:0] lshr_ln67_fu_1055_p2;
wire  signed [3:0] sext_ln70_fu_1093_p1;
wire   [4:0] or_ln4_fu_1105_p3;
wire   [4:0] zext_ln66_1_fu_1101_p1;
wire   [4:0] add_ln72_fu_1118_p2;
wire  signed [4:0] sext_ln73_fu_1129_p1;
wire  signed [4:0] sext_ln74_fu_1137_p1;
wire    ap_CS_fsm_state14;
reg   [11:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
end

sha256_k #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
k_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_address0),
    .ce0(k_ce0),
    .q0(k_q0)
);

sha256_m #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
m_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(m_address0),
    .ce0(m_ce0),
    .we0(m_we0),
    .d0(m_d0),
    .q0(m_q0),
    .address1(m_address1),
    .ce1(m_ce1),
    .q1(m_q1),
    .address2(m_address2),
    .ce2(m_ce2),
    .q2(m_q2),
    .address3(m_address3),
    .ce3(m_ce3),
    .q3(m_q3),
    .address4(m_address4),
    .ce4(m_ce4),
    .q4(m_q4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state4))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state4))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        a_3_reg_418 <= stateREG_i;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln37_reg_1241 == 1'd0))) begin
        a_3_reg_418 <= a_2_fu_1005_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_1_reg_395 <= 7'd16;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln23_reg_1158 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        i_1_reg_395 <= add_ln23_reg_1162;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_2_reg_407 <= 7'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_fu_699_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        i_2_reg_407 <= add_ln37_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_384 <= 5'd0;
    end else if (((icmp_ln20_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_384 <= add_ln20_fu_452_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        r_reg_428 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        r_reg_428 <= add_ln66_reg_1265;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        a_reg_1230 <= stateREG_i;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln23_fu_469_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln23_reg_1162 <= add_ln23_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln52_reg_1260 <= add_ln52_fu_1016_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln66_reg_1265 <= add_ln66_fu_1021_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1))) begin
        c_fu_202 <= a_3_reg_418;
        d_1_fu_198 <= c_fu_202;
        d_fu_194 <= d_1_fu_198;
        g_fu_186 <= f_fu_190;
        h_1_fu_182 <= g_fu_186;
        h_fu_178 <= h_1_fu_182;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln37_reg_1241 == 1'd0))) begin
        f_fu_190 <= e_fu_993_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln23_reg_1158 <= icmp_ln23_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln37_reg_1241 <= icmp_ln37_fu_699_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        or_ln22_1_reg_1145 <= or_ln22_1_fu_440_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_1027_p2 == 1'd0))) begin
        or_ln3_reg_1284[2 : 0] <= or_ln3_fu_1075_p3[2 : 0];
        trunc_ln67_1_reg_1273 <= trunc_ln67_1_fu_1060_p1;
        xor_ln68_reg_1278 <= xor_ln68_fu_1064_p2;
    end
end

always @ (*) begin
    if ((icmp_ln23_fu_469_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_fu_699_p2 == 1'd1))) begin
        ap_condition_pp2_flush_enable = 1'b1;
    end else begin
        ap_condition_pp2_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln23_reg_1158 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_i_1_phi_fu_399_p4 = add_ln23_reg_1162;
    end else begin
        ap_phi_mux_i_1_phi_fu_399_p4 = i_1_reg_395;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hash_address0 = zext_ln74_fu_1140_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hash_address0 = zext_ln72_fu_1124_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hash_address0 = zext_ln70_fu_1096_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hash_address0 = zext_ln69_fu_1083_p1;
    end else begin
        hash_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hash_address1 = zext_ln73_fu_1132_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hash_address1 = zext_ln71_fu_1113_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hash_address1 = zext_ln66_fu_1088_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        hash_address1 = zext_ln68_fu_1070_p1;
    end else begin
        hash_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10))) begin
        hash_ce0 = 1'b1;
    end else begin
        hash_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10))) begin
        hash_ce1 = 1'b1;
    end else begin
        hash_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hash_d1 = trunc_ln67_1_reg_1273;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10))) begin
        hash_d1 = 8'd0;
    end else begin
        hash_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_1027_p2 == 1'd0)))) begin
        hash_we0 = 1'b1;
    end else begin
        hash_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_1027_p2 == 1'd0)))) begin
        hash_we1 = 1'b1;
    end else begin
        hash_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        k_ce0 = 1'b1;
    end else begin
        k_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        m_address0 = zext_ln37_fu_705_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        m_address0 = zext_ln23_fu_529_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        m_address0 = zext_ln20_fu_464_p1;
    end else begin
        m_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
        m_ce0 = 1'b1;
    end else begin
        m_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m_ce1 = 1'b1;
    end else begin
        m_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m_ce2 = 1'b1;
    end else begin
        m_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m_ce3 = 1'b1;
    end else begin
        m_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m_ce4 = 1'b1;
    end else begin
        m_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        m_d0 = add_ln24_6_fu_686_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        m_d0 = or_ln22_1_reg_1145;
    end else begin
        m_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln23_reg_1158 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1)) | ((icmp_ln20_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        m_we0 = 1'b1;
    end else begin
        m_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        stateREG_o_ap_vld = 1'b1;
    end else begin
        stateREG_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln20_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln23_fu_469_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln23_fu_469_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_1027_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_2_fu_1005_p2 = (add_ln47_fu_999_p2 + xor_ln39_3_fu_987_p2);

assign add_ln20_fu_452_p2 = (i_reg_384 + 5'd1);

assign add_ln23_fu_475_p2 = (ap_phi_mux_i_1_phi_fu_399_p4 + 7'd1);

assign add_ln24_1_fu_496_p2 = ($signed(trunc_ln23_fu_481_p1) + $signed(6'd57));

assign add_ln24_2_fu_507_p2 = ($signed(trunc_ln23_fu_481_p1) + $signed(6'd49));

assign add_ln24_3_fu_518_p2 = ($signed(trunc_ln23_fu_481_p1) + $signed(6'd48));

assign add_ln24_4_fu_674_p2 = (m_q3 + m_q1);

assign add_ln24_5_fu_680_p2 = (xor_ln24_1_fu_598_p2 + xor_ln24_3_fu_668_p2);

assign add_ln24_6_fu_686_p2 = (add_ln24_5_fu_680_p2 + add_ln24_4_fu_674_p2);

assign add_ln24_fu_485_p2 = ($signed(trunc_ln23_fu_481_p1) + $signed(6'd62));

assign add_ln37_fu_693_p2 = (i_2_reg_407 + 7'd1);

assign add_ln38_1_fu_873_p2 = (xor_ln38_3_fu_861_p2 + xor_ln38_1_fu_837_p2);

assign add_ln38_2_fu_879_p2 = (add_ln38_1_fu_873_p2 + h_fu_178);

assign add_ln38_fu_867_p2 = (k_q0 + m_q0);

assign add_ln47_fu_999_p2 = (xor_ln39_1_fu_963_p2 + t1_fu_885_p2);

assign add_ln52_fu_1016_p2 = (a_reg_1230 + a_3_reg_418);

assign add_ln66_fu_1021_p2 = (r_reg_428 + 3'd1);

assign add_ln72_fu_1118_p2 = ($signed(zext_ln66_1_fu_1101_p1) + $signed(5'd20));

assign and_ln38_1_fu_855_p2 = (xor_ln38_2_fu_849_p2 & h_1_fu_182);

assign and_ln38_fu_843_p2 = (g_fu_186 & f_fu_190);

assign and_ln39_1_fu_981_p2 = (d_1_fu_198 & c_fu_202);

assign and_ln39_fu_975_p2 = (xor_ln39_2_fu_969_p2 & a_3_reg_418);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd6];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state4_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign e_fu_993_p2 = (t1_fu_885_p2 + d_fu_194);

assign hash_d0 = 8'd0;

assign icmp_ln20_fu_458_p2 = ((i_reg_384 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_469_p2 = ((ap_phi_mux_i_1_phi_fu_399_p4 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_699_p2 = ((i_2_reg_407 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1027_p2 = ((r_reg_428 == 3'd4) ? 1'b1 : 1'b0);

assign k_address0 = zext_ln37_fu_705_p1;

assign lshr_ln1_fu_765_p4 = {{f_fu_190[31:6]}};

assign lshr_ln24_1_fu_556_p4 = {{m_q4[31:19]}};

assign lshr_ln24_2_fu_578_p4 = {{m_q4[31:10]}};

assign lshr_ln24_3_fu_604_p4 = {{m_q2[31:7]}};

assign lshr_ln24_4_fu_626_p4 = {{m_q2[31:18]}};

assign lshr_ln24_5_fu_648_p4 = {{m_q2[31:3]}};

assign lshr_ln2_fu_891_p4 = {{a_3_reg_418[31:2]}};

assign lshr_ln38_1_fu_787_p4 = {{f_fu_190[31:11]}};

assign lshr_ln38_2_fu_809_p4 = {{f_fu_190[31:25]}};

assign lshr_ln39_1_fu_913_p4 = {{a_3_reg_418[31:13]}};

assign lshr_ln39_2_fu_935_p4 = {{a_3_reg_418[31:22]}};

assign lshr_ln67_fu_1055_p2 = add_ln52_reg_1260 >> zext_ln67_fu_1051_p1;

assign lshr_ln_fu_534_p4 = {{m_q4[31:17]}};

assign m_address1 = zext_ln24_3_fu_524_p1;

assign m_address2 = zext_ln24_2_fu_513_p1;

assign m_address3 = zext_ln24_1_fu_502_p1;

assign m_address4 = zext_ln24_fu_491_p1;

assign or_ln1_fu_779_p3 = {{trunc_ln38_fu_775_p1}, {lshr_ln1_fu_765_p4}};

assign or_ln22_1_fu_440_p5 = {{{{data}, {data}}, {data}}, {data}};

assign or_ln24_1_fu_570_p3 = {{trunc_ln24_1_fu_566_p1}, {lshr_ln24_1_fu_556_p4}};

assign or_ln24_2_fu_618_p3 = {{trunc_ln24_2_fu_614_p1}, {lshr_ln24_3_fu_604_p4}};

assign or_ln24_3_fu_640_p3 = {{trunc_ln24_3_fu_636_p1}, {lshr_ln24_4_fu_626_p4}};

assign or_ln2_fu_905_p3 = {{trunc_ln39_fu_901_p1}, {lshr_ln2_fu_891_p4}};

assign or_ln38_1_fu_801_p3 = {{trunc_ln38_1_fu_797_p1}, {lshr_ln38_1_fu_787_p4}};

assign or_ln38_2_fu_823_p3 = {{trunc_ln38_2_fu_819_p1}, {lshr_ln38_2_fu_809_p4}};

assign or_ln39_1_fu_927_p3 = {{trunc_ln39_1_fu_923_p1}, {lshr_ln39_1_fu_913_p4}};

assign or_ln39_2_fu_949_p3 = {{trunc_ln39_2_fu_945_p1}, {lshr_ln39_2_fu_935_p4}};

assign or_ln3_fu_1075_p3 = {{1'd1}, {r_reg_428}};

assign or_ln4_fu_1105_p3 = {{2'd2}, {r_reg_428}};

assign or_ln_fu_548_p3 = {{trunc_ln24_fu_544_p1}, {lshr_ln_fu_534_p4}};

assign sext_ln70_fu_1093_p1 = xor_ln68_reg_1278;

assign sext_ln73_fu_1129_p1 = or_ln3_reg_1284;

assign sext_ln74_fu_1137_p1 = xor_ln68_reg_1278;

assign shl_ln_fu_1037_p3 = {{trunc_ln67_fu_1033_p1}, {3'd0}};

assign stateREG_o = 32'd0;

assign sub_ln67_fu_1045_p2 = ($signed(5'd24) - $signed(shl_ln_fu_1037_p3));

assign t1_fu_885_p2 = (add_ln38_2_fu_879_p2 + add_ln38_fu_867_p2);

assign trunc_ln23_fu_481_p1 = ap_phi_mux_i_1_phi_fu_399_p4[5:0];

assign trunc_ln24_1_fu_566_p1 = m_q4[18:0];

assign trunc_ln24_2_fu_614_p1 = m_q2[6:0];

assign trunc_ln24_3_fu_636_p1 = m_q2[17:0];

assign trunc_ln24_fu_544_p1 = m_q4[16:0];

assign trunc_ln38_1_fu_797_p1 = f_fu_190[10:0];

assign trunc_ln38_2_fu_819_p1 = f_fu_190[24:0];

assign trunc_ln38_fu_775_p1 = f_fu_190[5:0];

assign trunc_ln39_1_fu_923_p1 = a_3_reg_418[12:0];

assign trunc_ln39_2_fu_945_p1 = a_3_reg_418[21:0];

assign trunc_ln39_fu_901_p1 = a_3_reg_418[1:0];

assign trunc_ln67_1_fu_1060_p1 = lshr_ln67_fu_1055_p2[7:0];

assign trunc_ln67_fu_1033_p1 = r_reg_428[1:0];

assign xor_ln24_1_fu_598_p2 = (xor_ln24_fu_592_p2 ^ or_ln_fu_548_p3);

assign xor_ln24_2_fu_662_p2 = (zext_ln24_5_fu_658_p1 ^ or_ln24_3_fu_640_p3);

assign xor_ln24_3_fu_668_p2 = (xor_ln24_2_fu_662_p2 ^ or_ln24_2_fu_618_p3);

assign xor_ln24_fu_592_p2 = (zext_ln24_4_fu_588_p1 ^ or_ln24_1_fu_570_p3);

assign xor_ln38_1_fu_837_p2 = (xor_ln38_fu_831_p2 ^ or_ln38_2_fu_823_p3);

assign xor_ln38_2_fu_849_p2 = (f_fu_190 ^ 32'd4294967295);

assign xor_ln38_3_fu_861_p2 = (and_ln38_fu_843_p2 ^ and_ln38_1_fu_855_p2);

assign xor_ln38_fu_831_p2 = (or_ln38_1_fu_801_p3 ^ or_ln1_fu_779_p3);

assign xor_ln39_1_fu_963_p2 = (xor_ln39_fu_957_p2 ^ or_ln39_2_fu_949_p3);

assign xor_ln39_2_fu_969_p2 = (d_1_fu_198 ^ c_fu_202);

assign xor_ln39_3_fu_987_p2 = (and_ln39_fu_975_p2 ^ and_ln39_1_fu_981_p2);

assign xor_ln39_fu_957_p2 = (or_ln39_1_fu_927_p3 ^ or_ln2_fu_905_p3);

assign xor_ln68_fu_1064_p2 = (r_reg_428 ^ 3'd4);

assign zext_ln20_fu_464_p1 = i_reg_384;

assign zext_ln23_fu_529_p1 = i_1_reg_395;

assign zext_ln24_1_fu_502_p1 = add_ln24_1_fu_496_p2;

assign zext_ln24_2_fu_513_p1 = add_ln24_2_fu_507_p2;

assign zext_ln24_3_fu_524_p1 = add_ln24_3_fu_518_p2;

assign zext_ln24_4_fu_588_p1 = lshr_ln24_2_fu_578_p4;

assign zext_ln24_5_fu_658_p1 = lshr_ln24_5_fu_648_p4;

assign zext_ln24_fu_491_p1 = add_ln24_fu_485_p2;

assign zext_ln37_fu_705_p1 = i_2_reg_407;

assign zext_ln66_1_fu_1101_p1 = r_reg_428;

assign zext_ln66_fu_1088_p1 = r_reg_428;

assign zext_ln67_fu_1051_p1 = sub_ln67_fu_1045_p2;

assign zext_ln68_fu_1070_p1 = $unsigned(xor_ln68_fu_1064_p2);

assign zext_ln69_fu_1083_p1 = $unsigned(or_ln3_fu_1075_p3);

assign zext_ln70_fu_1096_p1 = $unsigned(sext_ln70_fu_1093_p1);

assign zext_ln71_fu_1113_p1 = or_ln4_fu_1105_p3;

assign zext_ln72_fu_1124_p1 = add_ln72_fu_1118_p2;

assign zext_ln73_fu_1132_p1 = $unsigned(sext_ln73_fu_1129_p1);

assign zext_ln74_fu_1140_p1 = $unsigned(sext_ln74_fu_1137_p1);

always @ (posedge ap_clk) begin
    or_ln3_reg_1284[3] <= 1'b1;
end

endmodule //sha256
